# Conteúdo dos wireframes: (id, nome, status, servidor?, elementos, nota)
# status: E = já existe no site · P = parcial · N = novo
NAV = ('nav',)
SECOES = [
 ('A', 'Aquisição — site público', 'Quem chega por Google, indicação, QR da escola ou redes. Tudo aberto, sem cadastro.', [
  ('A1','Home pública','E',0,[('bar','Bicho no Bolso','Explorar · Comparar · Missões · Meu Bolso'),('img','foto real / Lupi',80),('h','Um mundo de bichos no seu bolso.'),('input','Procure um animal…'),('btn','Explorar bichos',1),('btn','Encontrei um!',0),('h2','Qual você quer descobrir?'),('chips',['Todos','Insetos','Aves','…']),('grid',4)],'Hero + busca + catálogo logo abaixo. Já existe (index.html).'),
  ('A2','Catálogo · busca e filtros','E',0,[('bar','Bicho no Bolso',''),('input','Procure um animal…'),('chips',['Todos','Insetos','Aves','Mamíferos']),('grid',6),('p','Sem resultado: "Nenhum bicho com esse nome."')],'Cartão: foto · nome · nome científico · curiosidade · tamanho/local/comida. Selo "Explorar em 3D" ou "Conhecer o bicho".'),
  ('A3','Ficha do animal','E',0,[('img','foto real',70),('h','Formiga-saúva'),('p','Atta spp.'),('chips',['Ficha','Vida','Sabia?','Real']),('btn','▶ Explorar em 3D',1),('btn','🔊 Ouvir',0),('btn','👀 Encontrei um de verdade!',0),('list',['Onde vive','O que come','Tamanho','Família'])],'Gaveta (sheet). Página própria por bicho (URL) ajudaria no Google: novo.'),
  ('A4','Experiência 3D · Modo Explorar','P',0,[('bar','← Formiga-saúva','Operária | Rainha | Zangão | Ninho'),('img','MODELO 3D GRANDE (50–65% da altura)',190),('side',['Ouvir','Partes','Tamanho','Folha','Andar','👁']),('lupi','Arraste para girar!'),('pill','✓ No meu bolso')],'Hoje: 3D pronto, interface antiga. Redesign: barra compacta, ações laterais, Partes, Tamanho real, modo sem interface.'),
  ('A5','Comparar · Qual é maior?','E',0,[('bar','← Qual bicho é maior?',''),('chips',['🐜','🐝','🦋','🐆']),('row',['foto A','VS','foto B']),('progress','Tamanho (escala)'),('p','"A onça é umas 150 vezes maior que a formiga!"'),('list',['São parentes?','O que comem','Quanto vivem'])],'Já existe (comparar.html).'),
  ('A6','/familias','N',0,[('bar','Bicho no Bolso','Começar grátis'),('h','Transforme curiosidade em aventura.'),('btn','Começar grátis',1),('row',['Encontre','Fotografe','Descubra','Colecione']),('p','Uma tela que convida a olhar para fora dela.'),('img','screenshots reais',60),('list',['Preços','Privacidade','FAQ'])],'Página de venda para adultos. Nada de cadastro antes do produto.'),
  ('A7','/escolas','N',0,[('bar','Bicho no Bolso Escolas',''),('h','Transforme o pátio da escola em laboratório.'),('row',['Antes: missão','Durante: turma','Depois: álbum']),('input','Nome · Escola · Cidade'),('input','E-mail institucional · nº de alunos'),('btn','Solicitar demonstração',1)],'Venda B2B: formulário, não checkout.'),
  ('A8','Preços','N',0,[('h','Planos'),('card','GRÁTIS · R$ 0 · catálogo, alguns 3D, álbum básico'),('card','FAMÍLIA · R$ 9,90/mês ou R$ 79,90/ano (hipótese)'),('card','ESCOLA · sob consulta'),('btn','Começar grátis',1),('p','Cancele quando quiser.')],'Preços são hipóteses de teste, não validados.'),
  ('A9','FAQ para adultos','N',0,[('h','Perguntas frequentes'),('list',['Para qual idade?','Precisa instalar?','Funciona no iPad?','Como as fotos são usadas?','Meu filho terá perfil público?','Como funciona a identificação?','Posso cancelar?'])],'Privacidade como argumento de confiança, não rodapé.'),
 ]),
 ('B', 'Primeiro uso', 'A criança brinca antes de qualquer conta. O adulto entra quando há motivo (guardar a carta).', [
  ('B1','Splash','E',0,[('dark',''),('img','logo + Lupi',110),('p','Um mundo de bichos no seu bolso.'),('p','bichos passando · toque para pular')],'~4 s no 1º acesso, ~1,5 s depois, nada na mesma sessão. Já existe.'),
  ('B2','Onboarding (3 passos)','N',0,[('img','Lupi com binóculo',120),('h','ENCONTRE'),('p','Veja um animal no jardim, parque ou escola.'),('dots',3),('btn','Próximo',1)],'Encontre → Descubra → Colecione. No máximo 3 telas. Hoje: "Olá, explorador!" (1 tela).'),
  ('B3','Olá, explorador!','E',0,[('img','Lupi',90),('h','Olá, explorador!'),('p','Vamos descobrir o mundo dos bichos?'),('btn','Começar a explorar',1),('btn','Sou responsável',0)],'Já existe. "Sou responsável" leva hoje à seção para adultos.'),
  ('B4','Primeira missão','E',0,[('bar','Bicho no Bolso',''),('card','🔎 Sua primeira missão: escolha um bicho para descobrir.'),('grid',4)],'Some depois do 1º bicho. Já existe.'),
  ('B5','Primeira descoberta','E',0,[('toast','🎉 Novo bicho no bolso! Formiga-saúva · 1 de 11'),('img','ficha / 3D',150),('p','🌱 Agora você é Curioso!')],'Já existe (salvo só no aparelho).'),
  ('B6','Guardar no bolso?','N',1,[('img','carta da Formiga #001',150),('h','Quer guardar sua primeira carta?'),('btn','Guardar no meu álbum',1),('btn','Continuar explorando',0)],'Só quando houver conta/sincronização. Hoje tudo já fica salvo no aparelho.'),
  ('B7','Chame um adulto (portão)','N',0,[('img','Lupi apontando',80),('h','Chame um adulto 👨‍👩‍👧'),('p','Um responsável precisa criar a conta.'),('p','Para continuar, quanto é 7 + 5?'),('row',['10','12','14']),('btn','Voltar a explorar',0)],'Portão parental simples (pergunta de adulto). Exigido em apps infantis.'),
  ('B8','Cadastro / login do responsável','N',1,[('h','Crie sua conta'),('p','Continue a coleção em qualquer aparelho.'),('btn','Continuar com Apple',0),('btn','Continuar com Google',0),('input','E-mail'),('input','Senha'),('btn','Criar conta grátis',1),('p','Aceito os termos e a política de privacidade')],'Mínimo de dados. Nada de endereço, telefone, gênero, escola.'),
  ('B9','Criar perfil do explorador','N',1,[('h','Quem é o explorador?'),('input','Apelido (ex.: Leo)'),('grid',6),('p','Escolha um avatar'),('btn','Criar explorador',1)],'Só apelido + avatar. Sem foto, sem data completa.'),
  ('B10','Quem vai explorar hoje?','N',1,[('h','Quem vai explorar hoje?'),('row',['🦊 Leo','🐸 Ana','➕ Novo']),('p','Área do responsável ›')],'Aparece ao abrir com conta. Família: vários perfis.'),
 ]),
 ('C', 'App da criança', 'Navegação: Explorar · Encontrar (centro, maior) · Meu Bolso · Missões. Perfil no avatar.', [
  ('C1','Home logada','P',0,[('bar','Bom dia, Leo!','avatar'),('h','Qual bicho vamos encontrar hoje?'),('btn','🔭 Procurar bichos',1),('btn','📷 Encontrei um!',0),('card','Missão do dia: observe um inseto'),('grid',3),NAV],'Hoje: saudação na splash e home pública. Falta a versão logada.'),
  ('C2','Explorar','E',0,[('bar','Explorar',''),('input','Procure um animal…'),('chips',['Todos','Insetos','Aves','…']),('grid',6),NAV],'= catálogo.'),
  ('C3','Ficha','E',0,[('img','foto',60),('h','Joaninha'),('pill','✓ No meu bolso · 👀 3'),('btn','Explorar em 3D',1),('btn','Ver tamanho real',0),('btn','Comparar',0),('list',['Onde vivo','O que como','Meu tamanho','Você sabia?']),NAV],'Já existe; falta "Ver tamanho real" e blocos mais visuais.'),
  ('C4','3D','P',0,[('img','MODELO 3D',220),('side',['Partes','Tamanho','Ouvir','👁']),NAV],'Ver A4.'),
  ('C5','Encontrar · câmera','N',1,[('cam',''),('p','Observe sem tocar. Chame um adulto.'),('row',['Galeria','📷','Dicas'])],'Foto com ajuda do adulto. Hoje: "Encontrei um!" escolhe da lista (sem foto).'),
  ('C6','Analisando…','N',1,[('img','foto tirada',150),('progress','Procurando o bicho…'),('lupi','Hmm… deixa eu ver!')],'Identificação no servidor (ex.: modelo de visão / iNaturalist).'),
  ('C7','Resultado · encontramos!','N',1,[('img','foto',120),('h','Olha quem encontramos!'),('p','Parece ser uma JOANINHA · 87% de confiança'),('btn','🔊 Ouvir curiosidade',0),('btn','Colocar no meu bolso',1)],'Nunca afirmar certeza que não existe.'),
  ('C8','Nova carta','P',0,[('dim',''),('card','#014 JOANINHA · 📷 Encontrada por mim'),('h','NOVO BICHO NO BOLSO!'),('p','carta desliza para dentro do bolso'),('btn','Ver no Meu Bolso',1)],'Hoje: aviso curto. Falta animação da carta entrando no bolso.'),
  ('C9','Meu Bolso','E',0,[('bar','Meu Bolso','3/11'),('card','🔎 Observador · faltam 3 para Explorador'),('progress','3 bichos no bolso'),('chips',['Todos','Encontrados','Ainda não']),('grid',9),NAV],'Já existe (cartas #001, pistas, níveis). Filtros: novo.'),
  ('C10','Coleções','N',0,[('h','Coleções'),('list',['🌻 Bichos do jardim 3/5','🪲 Insetos 2/4','🐦 Aves 0/2','🌊 Vida na água 0/2']),('p','FALTA SÓ UM!'),NAV],'Agrupa cartas. Completar = selo.'),
  ('C11','Carta individual · diário','P',0,[('img','frente: foto',110),('h','#004 Joaninha'),('p','Encontrada 3 vezes · 1ª vez: 12 out.'),('list',['📏 1–10 mm','🍽️ Pulgões','🌍 Mundo todo','💡 Curiosidade']),('grid',3),('p','minhas fotos (com conta)')],'Hoje: contagem de observações. Fotos/datas: com conta.'),
  ('C12','Missões','P',0,[('bar','Missões',''),('card','MISSÃO DO BOLSO · Pequenos do jardim 2/5'),('list',['☑ formiga','☐ abelha','☑ joaninha','☐ borboleta']),('card','Quem é maior? (em casa)'),NAV],'Hoje: 1 missão. Faltam missão do dia, cores, missões em casa.'),
  ('C13','Conquistas','N',0,[('h','Conquistas'),('grid',6),('p','🏅 Pequenos Gigantes · 🏅 De Pertinho · 🔒 ???'),NAV],'Surpresa: nem todas aparecem antes.'),
  ('C14','Passaporte do explorador','N',1,[('img','avatar',70),('h','LEO · 🔎 Observador'),('row',['18 bichos','27 obs.','4 conquistas']),('list',['Jardim 8/12','Insetos 11/30','Aves 4/25']),('p','Trocar explorador')],'Sem perfil social, sem ranking.'),
 ]),
 ('D', 'Área do responsável', 'Atrás do portão parental. Onde ficam assinatura, privacidade e dados.', [
  ('D1','Painel do responsável','N',1,[('bar','Área do responsável',''),('row',['Leo','Ana','+']),('card','Esta semana: 5 bichos, 2 missões'),('list',['Perfis','Assinatura','Privacidade e fotos','Histórico','Configurações'])],'Resumo útil, sem métricas de tempo de tela como meta.'),
  ('D2','Perfis','N',1,[('h','Exploradores'),('list',['🦊 Leo · editar · apagar','🐸 Ana · editar · apagar']),('btn','Novo explorador',1)],''),
  ('D3','Assinatura','N',1,[('h','Plano Família'),('card','Ativo · renova em 12/11 · R$ 9,90'),('btn','Mudar para anual',0),('btn','Cancelar assinatura',0)],'Cancelar tão fácil quanto assinar.'),
  ('D4','Privacidade e fotos','N',1,[('h','Privacidade'),('list',['Guardar fotos das descobertas: ligado','Apagar fotos após 90 dias','Localização: nunca pública','Quem vê o álbum: só a família']),('p','Política de privacidade ›')],'LGPD e proteção de crianças: revisar antes de lançar fotos.'),
  ('D5','Histórico','N',1,[('h','Descobertas'),('list',['12/10 · Joaninha (foto)','11/10 · Formiga (ficha)','10/10 · Missão completa'])],''),
  ('D6','Configurações','N',1,[('h','Configurações'),('list',['Sons: ligado','Voz da Lupi: desligado','Idioma','Sair'])],'Voz opcional (pedido do início: sem voz automática).'),
  ('D7','Exportar / excluir dados','N',1,[('h','Seus dados'),('btn','Baixar meus dados',0),('btn','Excluir conta e fotos',0),('p','Confirmação: digite EXCLUIR')],'Exclusão real e simples.'),
 ]),
 ('E', 'Escola e professor', 'Venda B2B por piloto. Professor cria turma e missões; álbum coletivo moderado.', [
  ('E1','/escolas (landing)','N',0,[('h','Transforme o pátio em laboratório.'),('row',['Antes','Durante','Depois']),('btn','Quero conhecer',1)],'Ver A7.'),
  ('E2','Cadastro do professor','N',1,[('h','Sou professor'),('input','Nome'),('input','E-mail institucional'),('input','Escola · Cidade'),('btn','Criar conta de professor',1)],'Vira lead de escola.'),
  ('E3','Painel do professor','N',1,[('bar','Painel','Prof. Ana'),('list',['Turma 1A · 24 alunos','Turma 2B · 22 alunos']),('btn','Nova turma',1),('btn','Nova missão',0)],''),
  ('E4','Criar turma','N',1,[('h','Nova turma'),('input','Nome (ex.: 1º ano A)'),('input','Nº aproximado de alunos'),('btn','Criar',1)],'Sem cadastro individual de criança.'),
  ('E5','Criar missão','N',1,[('h','Nova missão'),('input','Título: Insetos do pátio'),('chips',['Insetos','Aves','Qualquer']),('input','Prazo: sexta'),('btn','Publicar',1)],''),
  ('E6','Código / QR da turma','N',1,[('h','Entre na missão'),('img','QR CODE',120),('p','ou digite: BICHO-4F2'),('btn','Imprimir',0)],'iPads da escola entram sem contas individuais.'),
  ('E7','Álbum coletivo','N',1,[('h','NOSSA TURMA encontrou 11 espécies!'),('grid',6),('p','Professor aprova o que aparece')],'Cooperação, sem ranking individual.'),
  ('E8','Resultados da atividade','N',1,[('h','Resultado · Insetos do pátio'),('row',['27 obs.','11 espécies','✔ completa']),('list',['Joaninha 6','Formiga 9','Abelha 4']),('btn','Baixar relatório',0)],'Evidência pedagógica para renovação.'),
 ]),
 ('F', 'Estados que costumam ser esquecidos', 'Cada um precisa de texto, ilustração (Lupi) e saída clara.', [
  ('F1','Sem internet','E',0,[('img','Lupi',70),('h','Sem internet agora'),('p','Você ainda pode explorar os bichos guardados.'),('btn','Continuar offline',1)],'App já funciona offline (PWA). Falta a tela/aviso.'),
  ('F2','Câmera negada','N',0,[('img','Lupi',70),('h','Precisamos da câmera'),('p','Peça a um adulto para permitir nos Ajustes.'),('btn','Escolher uma foto',0),('btn','Voltar',0)],''),
  ('F3','Identificação incerta','N',1,[('img','foto',90),('h','Temos uma pista!'),('p','Parece um tipo de besouro. Vamos observar mais?'),('btn','Tirar outra foto',1),('btn','Pedir ajuda a um adulto',0)],'Não inventar precisão.'),
  ('F4','Não identificado','N',1,[('img','Lupi',70),('h','Ops! Não conseguimos descobrir esse bicho ainda.'),('btn','Tentar de novo',1),('btn','Escolher da lista',0)],''),
  ('F5','Álbum vazio','P',0,[('img','Lupi planejando',90),('h','Seu bolso está vazio'),('p','Vamos encontrar o primeiro bicho?'),('btn','Explorar bichos',1)],'Hoje: texto. Falta a ilustração.'),
  ('F6','Missão concluída','P',0,[('img','Lupi comemorando',90),('h','Missão completa!'),('p','🏅 Explorador do Jardim'),('btn','Ver selo',1)],'Hoje: aviso curto.'),
  ('F7','Limite grátis','N',1,[('h','Você usou as 5 identificações grátis do mês'),('p','O catálogo continua aberto.'),('btn','Conhecer o plano Família',1),('btn','Continuar explorando',0)],'Nunca bloquear conhecimento básico.'),
  ('F8','Paywall','N',1,[('h','A aventura está só começando.'),('p','Leo já encontrou 7 bichos.'),('card','FAMÍLIA · R$ 9,90/mês · ou R$ 79,90/ano'),('btn','Continuar a aventura',1),('btn','Continuar no plano grátis',0),('p','Cancele quando quiser.')],'Depois do hábito; botão grátis visível.'),
  ('F9','Assinatura ativa','N',1,[('img','Lupi comemorando',80),('h','Bem-vindos ao plano Família!'),('list',['Todos os 3D','Mais identificações','Coleções especiais']),('btn','Começar',1)],''),
  ('F10','Cancelamento','N',1,[('h','Cancelar o plano Família?'),('p','Vocês voltam ao plano grátis em 12/11. O bolso continua.'),('btn','Cancelar assinatura',0),('btn','Manter plano',1)],'Sem truques para dificultar.'),
 ]),
]
